### ISSUE TITLE
503 Over Quota

### ISSUE THREAD

**Issue by HugoSPT** [gregorym/boilerpipe#1]
I developed a tool using boilerpipe web and until now it works right. But now I'm getting this error all the time:"503 Service Unavailable".

I realize that http://boilerpipe-web.appspot.com/ is down. It has influence on my tool?

Regards,
Hugo

**Comment by gregorym** [comment]
Hey,

Yes boilerpipe relies on http://boilerpipe-web.appspot.com/ so if it is down it will not work. 
However you can specify an url to another url if you have one.

**Comment by ashif-ismail** [comment]
hey @HugoSPT ,
i was suffering from the same over quota error during my initial days,so i have created my own version of boilerpipe web API,you may find it usefull..

fork the project @  
https://github.com/SheikhZayed/offlinebrowser-web

try the demo @ 
http://offlinebrowser-web.appspot.com/
